create table reader(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       readerTicketNumber int NOT NULL UNIQUE check (readerTicketNumber>0 ),
                       name varchar NOT NULL ,
                       surname varchar NOT NULL ,
                       patronymic varchar NOT NULL ,
                       age int NOT NULL check ( age > 0),
                       gender varchar NOT NULL,
                       email varchar NOT NULL UNIQUE
);


create table book(
                     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     title varchar NOT NULL ,
                     author varchar NOT NULL ,
                     year int check ( year > 0 )

)